### ISSUE TITLE
help - wrong setting on theme_customcss

### ISSUE THREAD

**Issue by myrctech** [juliushaertl/theming_customcss#11]
hello everyone, 
I have wrongly put below and hide the whole site settings page.
.app-settings{display:none;}

 Can anyone guide me where can I reset the css setting, I couldn't figure out where this file is saved? thanks a lot!!

**Comment by blackcrack** [comment]
.app-settings {display:yourconfig !important ;}
this overwrite the configuration

i have make a theme : 
http://www.blackysgate.de/files/folder-root/nextcloud/

best regards
Blacky

**Comment by myrctech** [comment]
hello Blacky, 
I cannot access the page of putting the CSS code now,  where can I put that code in ?

thanks again!
RC

**Comment by blackcrack** [comment]
Hi @myrctech ,

want you make it as theme 
or want you manipulate directly in the Nextcloud code ?

you could take ff and on the place where you whant change it, 
right mouse and "Q inspect element" and then do you see where is the css code in which file..
in the header of the css-element right sided on bottom in the codeeditor.

best regards
Blacky

**Comment by myrctech** [comment]
thanks blacky, 
I don't get it very right, trying to figure it out.

do u think you know where exactly is the theme_customcss file stored, I suppose I can easily remove that as currently the display:none that I wrongly put it had removed all my view on the admin setting page.

**Comment by blackcrack** [comment]
@myrctech 
i be at moment not at home, but 
it should normally stored under 
/nextcloud/apps/theming_customcss
and there should anywhere the customizing..
could also store in a php.. you must easly search.. :)
maybe also with mc + F7 and search the text in the files..

best regards
Blacky

**Comment by myrctech** [comment]
Blacky,
sadly I have been digging into the folder, but couldn't figure it out so far....
appreciated so much for your guidance again

**Comment by blackcrack** [comment]
@juliushaertl ,

you be the master of disaster ;) could you help.. i be not at home ..

best regards
Blacky

**Comment by myrctech** [comment]
I have tried to remove the app, and reinstalled couple times, removing the whole directory /theme_customcss, and the same css config came back. So I suspecting the record was saved in db or somewhere else. But I still couldn't find it out



Appreciate for any help, thanks!

**Comment by juliushaertl** [comment]
The following occ command should remove the stored css from your app config:

```
occ config:app:delete theming_customcss customcss
```

You might need to force-reload the page afterwards to see the changes apply.

**Comment by myrctech** [comment]
@juliushaertl 
I just did the occ config, it did remove and disable the app. But when I download & enable it again, the same css config (the wrong) came back. 

did I miss some steps ? I did perform even a apache2 reload after removing the app.

thanks!

**Comment by myrctech** [comment]
Oo great , it works now.. 

thanks both @juliushaertl  @blackcrack

**Comment by blackcrack** [comment]
:+1: 
you're Welcome :smiley:
