### ISSUE TITLE
[Question] l10n

### ISSUE THREAD

**Issue by Valdnet** [juliushaertl/theming_customcss#15]
Is it possible to translate for this application?
It can add a translation to Transifex, or put a file in English in l10n.

**Comment by juliushaertl** [comment]
I'll have a look into getting this setup for transifex.

**Comment by juliushaertl** [comment]
Waiting for https://github.com/nextcloud/docker-ci/pull/387 to be merged

**Comment by juliushaertl** [comment]
Transifex sync is running 


https://github.com/juliushaertl/theming_customcss/commit/b9c3053a431f40ed5550d135e000dae23aa6bb6a
