### ISSUE TITLE
Where is the Config  File

### ISSUE THREAD

**Issue by Gustavo-FS** [juliushaertl/theming_customcss#16]
I made several configurations in an instance of the nextcloud that I needed to format

I have the backup files please does anyone know where the configuration file is located?

**Comment by juliushaertl** [comment]
There is no configuratino file, the custom css rules are stored in the database. You can get/set/delete them with the `occ config:app` commands as described in https://github.com/juliushaertl/theming_customcss/issues/12#issuecomment-581135497
