### ISSUE TITLE
Upload Logo by CLI

### ISSUE THREAD

**Issue by francoisPE** [juliushaertl/theming_customcss#18]
Hello,
I wonder if it is possible to upload logo or favicon by cli...
something like php occ config:app:set theming upload-logo --value="/my/path/to/logo/logo.svg"

Many thanks for your very usefull app !

**Comment by juliushaertl** [comment]
Not really related to this app (customcss) but should be possible these days with the server theming app: https://github.com/nextcloud/server/pull/23024

**Comment by blackcrack** [comment]
@francoisPE something works only at /themes/

example : https://www.blackysgate.de/files/folder-root/nextcloud/
