### ISSUE TITLE
Where are the settings?

### ISSUE THREAD

**Issue by JonCSgr** [juliushaertl/theming_customcss#19]
I installed this app but cant find any info to edit on settings . Where is the admin page located?

**Comment by porjo** [comment]
I had the same question. You should find them under Settings -> Administration -> Theming

<img src='https://user-images.githubusercontent.com/1296987/109728848-b7c74200-7c02-11eb-8050-6d9f89579d21.png' width=400>

**Comment by Ullarah** [comment]
I was also quite confused with a new v21 install.  The theming app isn't installed and it states that it's unstable.

Went to install it and broke my install and had to forcibly remove the app (even occ didn't work!).

However installing this customcss app worked fine and I can access it by changing the URL manually.

https://nextcloud/settings/admin/theming
