### ISSUE TITLE
Can't see the CSS app anymore

### ISSUE THREAD

**Issue by aredman2010** [juliushaertl/theming_customcss#20]
I think I may have inadvertently used CSS to hide the app (within the app) and I can no longer see the configuration options in Theming. Can you advise on where the actual configuration is when I log into my server?

Is it here or what directory is it in, etc.?
user@cloud:[/var/www/nextcloud/apps/theming_customcss]:

Thanks!

**Comment by juliushaertl** [comment]
The css configuration is stored in the app config database table, but you can use the `occ config:app:*` commands to obtain, modify or reset it as well:

```
occ config:app:get theming_customcss customcss
occ config:app:set theming_customcss customcss --value "body { background-color: red; }"
occ config:app:delete theming_customcss customcss
```
