### ISSUE TITLE
[Question] How do I tell it on which css I want the changes applied?

### ISSUE THREAD

**Issue by RobertRoberts2020** [juliushaertl/theming_customcss#22]
Hi,

this thing is great, I've been trying some configs but I don't know how to apply a certain change to a particular css.

For example, I want to change the login screen logo,  I can edit the #header .logo properties and it works, but since I'm not specifying I want the change done only in guest.css it also affects the logo that shows up on the top nextcloud bar and screws it.

Thanks.

**Comment by juliushaertl** [comment]
This is out of scope of the issue tracker of the app. If you need help with styling I'd recommend to ask in the forums at help.nextcloud.com
