### ISSUE TITLE
Question: @NoCSRFRequired

### ISSUE THREAD

**Issue by newhinton** [juliushaertl/theming_customcss#28]
Hello!

I am currently updating the splash app, and since i dont do much more than the custom css app, i have peeked a bit. 

Could you explain why your public api point has the @NoCSRFRequired-flag, and why it is nessessary?

In the security guidelines it is advised to not add it, but if i omit it on my endpoint, it fails to load.

Thank you for your help!

**Comment by juliushaertl** [comment]
Best place for such questions would be rather https://help.nextcloud.com/c/dev/11, but to give you a quick answer, omitting the CSRF check is usually fine for requests that do not involve any state changing. In this special case the endpoint is just returning a semi-static css which would make it not vulnerable to CSRF attacks. 

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html might give you a bit more insight on the actual security topic.

The reason why it doesn't work with the CSRF requirement is, that the the token is not added for styles/scripts loaded by the browser.


Hope that helps :)
