### ISSUE TITLE
css-variables.scss

### ISSUE THREAD

**Issue by alphagold** [juliushaertl/theming_customcss#29]
https://github.com/nextcloud/server/blob/master/core/css/css-variables.scss

not found

**Comment by juliushaertl** [comment]
Until Nextcloud 25 is released you may want to check https://github.com/nextcloud/server/blob/stable24/core/css/css-variables.scss for Nextcloud 24

**Comment by alphagold** [comment]
Thank you very much.
As I'm not that great at generating css code.
If I wanted to apply as default google "Monserrat" what code should I enter?
Congratulations on your commitment!
Thank you
