### ISSUE TITLE
Loading the stylesheet causes redirects

### ISSUE THREAD

**Issue by pdobrigkeit** [juliushaertl/theming_customcss#32]
Not sure if this is an issue with our installation or how to debug this, but sometimes (not always) the call to load the custom defined css under `index.php/apps/theming_customcss/styles?v=1658401527704` causes 302 redirects and then the custom CSS is obviously not applied to the page. Any idea what might be causing this behaviour?

![Marketplace](https://user-images.githubusercontent.com/1052961/182340065-22aeeb1a-59e9-4227-9c83-90257398356e.png)

**Comment by juliushaertl** [comment]
I cannot think of anything causing this only partly. Can you reproduce this redirect using curl?

**Comment by juliushaertl** [comment]
Closing due to lack of feedback, but feel free to reopen if this still happens.
