### ISSUE TITLE
Issue with NC25 : logo header

### ISSUE THREAD

**Issue by francoisPE** [juliushaertl/theming_customcss#33]
Hello,
I switch from 24 to 25 and I face several issues.
I used apporder and see that it no more works. It was so fun. But I solved using side_menu where I found that almost same capability ...
![image](https://user-images.githubusercontent.com/60675606/215271226-ccf04519-2768-4e31-8407-352ae6d94d76.png)

But, I still have an issue : my logo header is not used. In header I have my logo.
How can I solve that ?
Thank you

**Comment by juliushaertl** [comment]
GitHub is for tracking issues with the app itself. For questions on specific styling and support with that please ask in the Nextcloud forum at help.nextcloud.com

**Comment by juliushaertl** [comment]
Or at the side menu repo https://gitnet.fr/deblan/side_menu ;)
