### ISSUE TITLE
404 on link in https://github.com/juliushaertl/theming_customcss/README.md

### ISSUE THREAD

**Issue by nursoda** [juliushaertl/theming_customcss#35]
current: https://github.com/nextcloud/server/blob/master/core/css/css-variables.scss
correct: https://github.com/nextcloud/server/blob/master/core/css/variables.scss

**Comment by juliushaertl** [comment]
Thanks, fixed with https://github.com/juliushaertl/theming_customcss/commit/39234b23e04c447235648ca744ccf50d4e337f2b

https://github.com/nextcloud/server/blob/master/apps/theming/css/default.css is actually the more relevant reference
