### ISSUE TITLE
Request: support External Sites app

### ISSUE THREAD

**Issue by sunjam** [juliushaertl/theming_customcss#5]
Currently Custom CSS just supports server themes.  Please consider supporting the [External Sites](https://github.com/nextcloud/external) app as well, since custom css would add a lot of helpful flexibility to how pages are displayed in that app.  See [Issue #8413](https://github.com/nextcloud/server/issues/8413)

**Comment by juliushaertl** [comment]
It is not supported by any browser to overwrite the css in a iframe, as the external sites app uses it, so this is not possible.

**Comment by juliushaertl** [comment]
You should be able to hide the nextcloud header in general with the custom css app btw. since you refer to server#8413

**Comment by sunjam** [comment]
I’m mounting _Box B_ Nextcloud Bookmarks and Tasks app on my _Box A_ Nextcloud localhost instance, which does not have either app installed, through the External Sites app.  Added the appropriate svg icons, and got both urls working via redirect.  Looks as though it is installed locally!
![3d9cb1a3-88bd-4c5f-b82f-7b064f5c4b2d](https://user-images.githubusercontent.com/1787238/36395951-9a0ec6bc-1570-11e8-9155-45aad8127b29.png)

The problem is once I access either external site I’m looking at the header of _Box B_ Nextcloud instance, when I just need to continue seeing the header of _Box A_.
    
I’d love for a way to continue seeing the same header on the external redirect, or at least some refined way to jump back to it from the external redirect.

**Comment by juliushaertl** [comment]
There's no way around that, since it is a redirect :wink: When disabling the redirect you can load the external site while keeping the header. 

Anyway, please head over to the forum for further discussion/questions regarding your use case, since that is out of scope of the customcss app.
