### ISSUE TITLE
Boilerplate Login screen overrides for v12.0.5

### ISSUE THREAD

**Issue by winstonford** [juliushaertl/theming_customcss#6]
Gutentog Julius :)

Thanks for the app!  No problems, just wanted to share style overrides to the login page.

Not sure if this is the place to share this, but here is a boilerplate to override login page styles to simplify and modernize the look a bit:

https://gist.github.com/winstonford/117d42a7cfb02a9e56aa74c8f1560c73

It should not affect anything once logged in, and looks mostly consistent for me on Mac + iOS on safari and chrome.  I did a browsershot and looked fine on windows, but no testing beyond that.

Happy for you to fold it into your repo here.  Whatever is easiest.  Just wanted to share and save someone time!

Best,
W

**Comment by juliushaertl** [comment]
Thanks for the comment. The styles seem to be very specific to your setup, so I don't think they can be used by other out of the box. We probably could have a wiki page with common classes/ids for adding css attributes to, but I won't be able to maintain that, so I'd rather just keep it up to everyone themselves to find the right element they want to style. :wink: 

Btw. https://gist.github.com/winstonford/117d42a7cfb02a9e56aa74c8f1560c73#file-nextcloud-css-overrides-L3 also affects the logo in the logged in layout. You should probably use `#body-login #header .logo-icon`

**Comment by winstonford** [comment]
Yes makes sense to me.  Thanks for the logo tip!
